[package]

name          = "mio"
version       = "0.2.1"
license       = "MIT"
authors       = ["Carl Lerche <me@carllerche.com>"]
description   = "Lightweight non-blocking IO"
documentation = "https://carllerche.github.io/mio/mio"
homepage      = "https://github.com/carllerche/mio"
repository    = "https://github.com/carllerche/mio"
readme        = "README.md"
keywords      = ["io", "async", "non-blocking"]
exclude       = [
  ".gitignore",
  ".travis.yml",
  "deploy.sh",
  "test/**/*",
]

[dependencies]
log   = "0.2.3"
time  = "0.1.16"
bytes = "0.1.2"

[dependencies.nix]
nix = "https://github.com/carllerche/nix-rust"

[dev-dependencies]
env_logger = "0.2.2"

[[test]]

name = "test"
path = "test/test.rs"
